add gaia dr3/edr3 filters
desihub/speclite pull request #83
Opened 2024-01-09 21:17 UTC by segasai

Hi, I added gaia dr3/edr3 filters

It fixes #80

The following code
```python
import speclite.filters
gdr3 = speclite.filters.load_filters('gaiadr3-*')
speclite.filters.plot_filters(gdr3)
```
produces this
![image](https://github.com/desihub/speclite/assets/109513/da21ae18-a22a-4acc-be4a-fc5bd54c3d19)

Just in case, I also include the code that I used to generate the .ecsvs
```

import astropy.table as atpy, astropy.units as auni
import numpy as np

T = atpy.Table().read('GaiaEDR3_passbands_zeropoints_version2/passband.dat',
                      format='ascii')

for i in range(3):
    val = T['col%d' % (i * 2 + 2)]  # col2 for i=0
    e_val = T['col%d' % (i * 2 + 3)]
    xind = np.nonzero((val != 99.99) & (val > e_val)
                      & (val > (1e-6 * val.max())))[0]
    N = len(xind)
    x0, x1 = xind[0], xind[-1]
    if x0 > 0:
        x0 = x0 - 1
    if x1 < len(val) - 1:
        x1 = x1 + 1
    xind = slice(x0, x1 + 1)
    val = val[xind] * 1
    val[0] = 0
    val[-1] = 0
    TT = atpy.Table({
        'wavelength': T['col1'][xind] * 10 * auni.Angstrom,
        'response': val
    })
    band = ['G', 'BP', 'RP'][i]
    TT.meta['url'] = 'https://www.cosmos.esa.int/web/gaia/edr3-passbands'
    TT.meta['group_name'] = 'gaiadr3'
    TT.meta['band_name'] = band
    TT.meta['airmass'] = 0
    TT.meta[
        'description'] = f'Bandpass for Gaia {band} band for DR3/EDR3 release'
    TT.write(f'gaiadr3-{band}.ecsv', overwrite=True)
```

2024-01-09 22:17 UTC, dkirkby commented
This looks good to me. Thanks @segasai.

2024-01-09 23:00 UTC, moustakas requested changes
Thanks @segasai. Before I approve, can you also please update the documentation by adding a figure of the filters to `docs/_static` directory and a brief description of the filter curves (especially any references or caveats) to `docs/filters.rst`, please?

2024-01-10 00:30 UTC, segasai commented
Thanks @moustakas, I applied the changes that you asked.

2024-01-10 01:02 UTC, moustakas approved these changes

2024-01-10 01:02 UTC, merged